### ISSUE TITLE
Create a docker-based development environment

### ISSUE THREAD

**Issue by bbaayezi** [node-red-quantum/node-red-contrib-quantum#53]
### Enhancement Description
As reported by two team members that they both encountered issues while setting up the development environment, I think it would be great to set up an easy docker-based dev environment to eliminate possible bugs across different OS platforms. Since it's an easy task I'm happy to work on it.

### Potential Issues

Docker environment needed.

**Comment by louislefevre** [comment]
I agree, a Docker environment would be ideal. I haven't used Docker myself, so would be great if you could set something up @bbaayezi.

**Comment by Theo-Reignier** [comment]
Good idea, we indeed need to make these environment-related bugs disappear.
 
However, being not familiar with Docker, I just want to insist on the fact that this solution should be easy and straightforward on the user end.
 
 Thanks @bbaayezi !

**Comment by Theo-Reignier** [comment]
Good idea, we indeed need to make these environment-related bugs disappear.
 
However, being not familiar with Docker, I just want to insist on the fact that this solution should be easy and straightforward on the user end.
 
 Thanks @bbaayezi !
