### ISSUE TITLE
Quantum Circuit EventEmitters not being removed

### ISSUE THREAD

**Issue by louislefevre** [node-red-quantum/node-red-contrib-quantum#78]
### Bug Description
`circuitReady` listeners are not being removed and eventually exceed the limit.

### Steps to Reproduce Bug

Running a circuit multiple times whilst in the same Node-RED session will eventually result in the following warning message:  
`MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 circuitReady listeners added to [EventEmitter].`

### Expected Behaviour & Actual Behaviour
Expected behaviour is that the listeners should be removed once they are no longer required.
Actual behaviour is that the listeners are never being removed.

### Additional Information
Perhaps replacing `event.on('circuitReady', ...` with `event.once('circuitReady', ...` in `quantum-circuit.js` may be the easiest solution? This ensures that the listener is only triggered once and is then removed. However, I'm not sure how this code works so I don't know if it'll work perfectly. Also, only one event emitter is being created: `const quantumCircuitReady = new EventEmitter();`. This single event emitter is being used for every quantum circuit node, rather than each node having its own `EventEmitter` object. Perhaps it would help to move this object creation into the `QuantumCircuitNode` function to avoid this.

### System Information
* **Node.js Version**: v16.6.2
* **Operating System**: Arch Linux (5.13.9)

**Comment by bbaayezi** [comment]
Change `event.on('circuitReady', ...` with `event.once('circuitReady', ...` seems to fix this issue indeed
